from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth','0012_alter_user_first_name_max_length')]
    operations = [
        migrations.CreateModel(name='Product',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(max_length=80,unique=True)),('description',models.CharField(max_length=255)),('unit',models.CharField(default='UN',max_length=10)),('min_stock',models.DecimalField(decimal_places=3,default=0,max_digits=14)),('imei_control',models.BooleanField(default=False)),('active',models.BooleanField(default=True))]),
        migrations.CreateModel(name='Address',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(max_length=40,unique=True)),('aisle',models.CharField(blank=True,max_length=20)),('level',models.PositiveIntegerField(default=1)),('capacity',models.DecimalField(decimal_places=3,default=0,max_digits=14)),('active',models.BooleanField(default=True))]),
        migrations.CreateModel(name='Lot',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(max_length=80)),('expiry',models.DateField(blank=True,null=True)),('product',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='wms.product'))]),
        migrations.CreateModel(name='Receipt',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('number',models.CharField(max_length=40,unique=True)),('invoice',models.CharField(blank=True,max_length=50)),('supplier',models.CharField(max_length=255)),('received_at',models.DateTimeField(auto_now_add=True)),('status',models.CharField(choices=[('OPEN','Aberta'),('CHECKING','Conferindo'),('DONE','Finalizada'),('DIVERGENCE','Divergência')],default='OPEN',max_length=20))]),
        migrations.CreateModel(name='Order',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('number',models.CharField(max_length=50,unique=True)),('customer',models.CharField(blank=True,max_length=255)),('priority',models.PositiveIntegerField(default=5)),('status',models.CharField(choices=[('RECEIVED','Recebido'),('RELEASED','Liberado'),('PICKING','Em separação'),('PICKED','Separado'),('SHIPPED','Expedido'),('CANCELLED','Cancelado')],default='RECEIVED',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='Picking',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('number',models.CharField(max_length=40,unique=True)),('status',models.CharField(choices=[('OPEN','Aberta'),('RELEASED','Liberada'),('RUNNING','Em execução'),('DONE','Concluída')],default='OPEN',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name='ReceiptItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('expected',models.DecimalField(decimal_places=3,max_digits=14)),('received',models.DecimalField(decimal_places=3,default=0,max_digits=14)),('lot_code',models.CharField(blank=True,max_length=80)),('expiry',models.DateField(blank=True,null=True)),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='wms.product')),('receipt',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='wms.receipt'))]),
        migrations.CreateModel(name='OrderItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.DecimalField(decimal_places=3,max_digits=14)),('picked',models.DecimalField(decimal_places=3,default=0,max_digits=14)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='wms.order')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='wms.product'))]),
        migrations.CreateModel(name='Stock',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.DecimalField(decimal_places=3,default=0,max_digits=14)),('reserved',models.DecimalField(decimal_places=3,default=0,max_digits=14)),('blocked',models.DecimalField(decimal_places=3,default=0,max_digits=14)),('address',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='wms.address')),('lot',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,to='wms.lot')),('product',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='wms.product'))]),
        migrations.CreateModel(name='PickingItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.DecimalField(decimal_places=3,max_digits=14)),('picked',models.DecimalField(decimal_places=3,default=0,max_digits=14)),('address',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='wms.address')),('order_item',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='wms.orderitem')),('picking',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='wms.picking'))]),
        migrations.CreateModel(name='Movement',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.DecimalField(decimal_places=3,max_digits=14)),('movement_type',models.CharField(choices=[('TRANSFER','Transferência'),('IN','Entrada'),('OUT','Saída'),('ADJUST','Ajuste'),('BLOCK','Bloqueio'),('UNBLOCK','Desbloqueio')],max_length=20)),('reference',models.CharField(blank=True,max_length=80)),('created_at',models.DateTimeField(auto_now_add=True)),('destination',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='movement_destination',to='wms.address')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='wms.product')),('source',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name='movement_source',to='wms.address')),('user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user'))]),
        migrations.AddConstraint(model_name='lot',constraint=models.UniqueConstraint(fields=('product','code'),name='wms_lot_product_code_uniq')),
        migrations.AddConstraint(model_name='stock',constraint=models.UniqueConstraint(fields=('product','address','lot'),name='wms_stock_product_address_lot_uniq')),
    ]
